import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'
import { ToastContainer, toast } from 'react-toastify';
import type { Metadata } from "next";
import { Toaster } from "@/components/ui/toaster"
import "./globals.css";
import Header from '@/components/header';
import SideBar from '@/components/SideBar';




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en" suppressHydrationWarning>
      
      <body>
      <ToastContainer />
        <Header/>
        <div className='flex min-h-screen'>
          <SideBar/>
          <div className='flex-1 bg-gray-100 p-2'>

          {children}
          </div>
    </div>
        </body>
    </html>
    </ClerkProvider>
  );
}
